DIRECTORY:
  original_data: /workspace/template_project/image_classification/data/sample10/
  original_splitted_data: /workspace/template_project/image_classification/data/sample10_splitted/
  preprocessed_data: /workspace/template_project/image_classification/data/preprocessed/
  system_log: /workspace/template_project/image_classification/log/
  performance_record: /workspace/template_project/image_classification/result/train/

SEED:
  random_seed: 42

SPLIT_DATA:
  train_ratio: 0.8
  validation_ratio: 0.1
  test_ratio: 0.1
  is_stratify: True

TRAIN:
  model: DNN  # DNN 
  n_input: 784
  n_output: 10
  batch_size: 8
  epoch: 10
  learning_rate: 0.0001
  momentum: 0.5
  optimizer: sgd  # SGD
  loss_function: nll  # nll
  metric_function: accuracy # accuracy
  early_stopping_patience: 5

DATALOADER:
  num_workers: 16
  shuffle: True
  pin_memory: True
  drop_last: True

PERFORMANCE_RECORD:
  column_list: 
    - experiment_serial
    - experiment_timestamp
    - model_str
    - optimizer_str
    - loss_function_str
    - metric_function_str
    - early_stopping_patience
    - batch_size
    - epoch
    - learning_rate
    - momentum
    - random_seed
    - epoch_index
    - train_loss
    - validation_loss
    - train_score
    - validation_score
    - is_early_stop