DIRECTORY:
  original_data: /workspace/template_project/image_classification/data/original/
  original_splitted_data: /workspace/template_project/image_classification/data/original_splitted/
  preprocessed_data: /workspace/template_project/image_classification/data/preprocessed/
  system_log: /workspace/template_project/image_classification/log/

SEED:
  random_seed: 42

SPLIT_DATA:
  train_ratio: 0.8
  validation_ratio: 0.1
  test_ratio: 0.1
  is_stratify: True